spring:
    application:
        name: a2spreparation
    datasource:
        url: jdbc:oracle:thin:@141.94.250.58:1521/xe
        username: PHARM2021
        password: xeon
        driver-class-name: oracle.jdbc.OracleDriver
